### ISSUE TITLE
No Plotting Functions

### ISSUE THREAD

**Issue by danielsengkey** [omnetpp/omnetpp-resultfiles#10]
I am using R v3.1.2 on Ubuntu 14.04.1 x86_64.
While I'm trying to plot a graph from my vectors, R warned me that plotLineChart is not exist.
The same thing happened when I tried to execute makeBarChartDataset() and makeHistogram.
![screenshot from 2015-03-02 13 48 02](https://cloud.githubusercontent.com/assets/10163132/6436484/f633f416-c0e2-11e4-8093-47709d6cf866.png)

Otherwise, functions to load data from result files are working well.

**Comment by kingaM** [comment]
I'm not really an expert and I never tried those functions out, but have you looked at the tutorial? Those functions take 2 arguments, whereas you are trying it with none.

**Comment by danielsengkey** [comment]
Hi,
Thanks for your response.
My problem the functions are not exist (could not be found by R). The screenshot was only an example showing error message retruned by R. AFAIK If the function lack of argument then R will give a message about missing argument.

**Comment by mightyCelu** [comment]
The functions have been removed in 9de6276025ad62dc4b05ccf9fb55f531a765a9ed. The documentation has also been updated in 4c8ef8da71b4ef9abeeb2f950e2071b39ced3ed9 but the wiki isnt.
